site_name: Proyecto 2do Quatrimestre
site_url: https://gss-mtig.github.io/proy2Q/
site_description: Proyecto 2do Quatrimestre
site_author: proy2Q
theme:
  name: 'material'
  language: 'es'
  highlightjs: true

markdown_extensions:
  - codehilite:
      linenums: True
  - admonition
  - pymdownx.magiclink
  - pymdownx.superfences
  - footnotes
repo_url: "https://github.com/gss-mtig/proy2Q"

nav:
- Home: index.md
- Levantamiento de requerimientos: requerimientos.md
- Requerimientos App: requerimientos_app.md
- Casos de uso: casos_uso.md
- Estructura del proyecto: estructura.md
- Contacto: contact.md
- Acerca de: about.md
- Página principal: principal.md
- Lista de incidencias: lista.md
- Formulario: formulario.md
- Menú: menu.md
- Mapa: mapa.md
- Controles y capas mapa: mapa_capas.md
- Lista Incidencias: lista_incidencias.md
- Servidor: servidor.md
- Mapa incidencias: mapa_incidencias.md

plugins:
    - search
